//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 06:07:52 PM AEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.ctiwebservice.com/xml/school", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ctiwebservice.xml.school;
